### ISSUE TITLE
[UX/UI] [Enhancement] Make light/dark mode fade time/properties consistent

### ISSUE THREAD

**Issue by CelluloidRacer2** [xornet-cloud/Xornet#158]
When changing the interface between light and dark mode, the timing varies causing some components to complete their transitions faster. 

See below for example:

![xbTcS2l26r](https://user-images.githubusercontent.com/10578386/123166028-8e912280-d43a-11eb-8c4e-5b46b2883775.gif)

**Comment by CelluloidRacer2** [comment]
Double title change because I don't proofread / think enough :P

**Comment by CelluloidRacer2** [comment]
@Geoxor can you mark why you closed this? Just figure it's good in case someone else finds the issue and opens one

**Comment by Geoxor** [comment]
I fixed this as much as possible on a commit, it's only the buttons that fade slowly but the rest is consistent now, we can't change the transition speed on the buttons because it's required for their hover animation theres probably ways to solve this by applying a temporary class to all of them that removes the transition speed while switching to darkmode, but its too much effort
